build: fix buidling gcc 10 and keep patches here. The reason why building gcc 10 broke is because asan_linux.cc moved to C+/cpp. Also potentially fixed building gcc 4.9.4 as the patch file was no longer on master.
Source of the patch files:
1: https://github.com/buildroot/buildroot/blob/2019.05.x/package/gcc/4.9.4/942-asan-fix-missing-include-signal-h.patch
2: kras@raphielgang.org for all the others.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -523,30 +523,6 @@ function update_repos() {
 }
 
 
-# Fetch required GCC patches
-function fetch_patches() {
-    mkdir -p patches
-    cd patches || die "Failed to create patches directory!"
-
-    if [[ ${VERSION} -eq 4 ]]; then
-        # GCC 4.9 (ARM/i686): error: ‘SIGSEGV' was not declared in this scope
-        GCC_PATCH="942-asan-fix-missing-include-signal-h"
-        [[ ! -f ${GCC_PATCH}.patch ]] && curl -sLO https://raw.githubusercontent.com/buildroot/buildroot/master/package/gcc/4.9.4/${GCC_PATCH}.patch
-    elif [[ ${VERSION} -ge 6 ]]; then
-        if [[ ${VERSION} -le 8 ]]; then
-            # GCC 6-8 (i686): error: ‘PATH_MAX' undeclared here (not in a function)
-            GCC_PATCH="53faaf1da220f5e904a1e8c8b343e91121218f82"
-        else
-            # GNU GCC 9 (any): error: ‘PATH_MAX' was not declared on this scope
-            GCC_PATCH="55a6998c4d5ce0ccd20bb0572915c2c94c0dc138"
-        fi
-        [[ ! -f ${GCC_PATCH}.patch ]] && curl -sLO https://gist.githubusercontent.com/krasCGQ/9e859c91e2e7c1fe0ffe009f4edd1d22/raw/114f29c50c15db2bc4ca9c2de348ad0fb3055ad1/${GCC_PATCH}.patch
-    fi
-
-    cd ..
-}
-
-
 # Setup source folders and build folders
 function setup_env() {
     INSTALL=${ROOT}/${TARGET}
@@ -574,9 +550,22 @@ function setup_env() {
         ln -s -f "${ROOT}/isl" isl
     fi
 
-    if [[ -n ${GCC_PATCH} ]]; then
-        patch -Np1 < "${ROOT}"/patches/${GCC_PATCH}.patch || die "Failed to patch GCC source!"
+    if [[ ${VERSION} -eq 4 ]]; then
+        # GCC 4.9 (ARM/i686): error: ‘SIGSEGV' was not declared in this scope
+        GCC_PATCH="942-asan-fix-missing-include-signal-h"
+    elif [[ ${VERSION} -ge 6 ]] && [[ ${VERSION} -le 8 ]]; then
+        # GCC 6-8 (i686): error: ‘PATH_MAX' undeclared here (not in a function)
+        GCC_PATCH="GCC_6-8"
+    elif [[ ${VERSION} -eq 9 ]]; then
+        # GNU GCC 9: error: ‘PATH_MAX' was not declared on this scope
+        GCC_PATCH="GCC_9"
+    else
+        # GNU GCC 10 (any): error: ‘PATH_MAX' was not declared on this scope
+        GCC_PATCH="GCC_10_up"
     fi
+
+    patch -Np1 < "${ROOT}"/patches/${GCC_PATCH}.patch || die "Failed to patch GCC source!"
+
     cd ..
 
     if [[ -z ${VERBOSE} ]]; then
@@ -723,7 +712,6 @@ build_binaries
 download_sources
 extract_sources
 update_repos
-fetch_patches
 setup_env
 build_binutils
 build_headers
