build: Make script silent by default
Errors will still be shown.

Suggested-by: Sultan Alsawaf <sultanxda@gmail.com>
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -49,7 +49,8 @@ function help_menu() {
     echo "  -nt | --no-tmpfs:    Do not use tmpfs for building (useful if you don't have much RAM)."
     echo "  -nu | --no-update:   Do not update the downloaded components before building (useful if you have slow internet)."
     echo "  -p  | --package:     Possible values: gz or xz. Compresses toolchain after build."
-    echo "  -t  | --tarballs:    Use tarballs for binutils, ISL, and, GCC\n"
+    echo "  -t  | --tarballs:    Use tarballs for binutils, ISL, and, GCC"
+    echo "  -V  | --verbose:     Make script print all output, not just errors and the ending information\n"
 }
 
 
@@ -67,6 +68,7 @@ function header() {
 
 # Prints an error in bold red
 function die() {
+    [[ ! ${VERBOSE} ]] && exec 1>&5 2>&6
     echo ""
     echo "${RED}${1}${RST}"
     [[ ${2} =~ "-n" ]] && echo
@@ -166,6 +168,7 @@ function parse_parameters() {
             "-nu"|"--no-update") UPDATE=false ;;
             "-p"|"--package") shift && COMPRESSION=${1} ;;
             "-t"|"--tarballs") TARBALLS=true ;;
+            "-V"|"--verbose") VERBOSE=true ;;
 
             # HELP!
             "-h"|"--help") help_menu; exit ;;
@@ -173,6 +176,8 @@ function parse_parameters() {
 
         shift
     done
+
+    [[ ! ${VERBOSE} ]] && exec 6>&2 5>&1 &>/dev/null
 
     # Default values
     case "${ARCH}" in
@@ -546,6 +551,7 @@ function package_tc() {
 function ending_info() {
     END=$(date +%s)
 
+    [[ ! ${VERBOSE} ]] && exec 1>&5 2>&6
     if [[ -e ${TARGET}/bin/${TARGET}-gcc ]]; then
         header "BUILD SUCCESSFUL"
         echo "${BOLD}Script duration:${RST} $(format_time "${START}" "${END}")"
